### ISSUE TITLE
Unexpected keys in {Yahp Class} error

### ISSUE THREAD

**Issue by vedantroy** [mosaicml/yahp#136]
Config:

```
mae:
  lr: 1.5e-4
  weight_decay: 0.05
  t_warmup_factor: 0.01
  t_max_factor: 1
  model: mae_vit_base_patch16
  model_overrides:
    # video has resolution unknown x 180
    # patch size = 16px
    # 14 * 12 = 168
    image_size: 168
run:
  device: gpu
  precision: fp32
  checkpoints: 10
  evals: 100
  duration: 10hr
  batch_size: 4096
  micro_batch_size: 128
  batches_per_sec: 2
  dl_workers: 8
```

Yahp classes:

```
from typing import Dict, Optional
from dataclasses import dataclass

import yahp as hp

@dataclass
class MaeVITParams(hp.Hparams):
    image_size: int = hp.required("Image size (after cropping)")

@dataclass
class MAEParams(hp.Hparams):
    lr: float = hp.required("Learning rate")
    weight_decay: float = hp.required("Weight decay")
    t_warmup_factor: int = hp.required("Warmup batches")
    t_max_factor: int = hp.required("Total batches")
    model: str = hp.required("The model type")
    model_overrides: MaeVITParams = hp.required("Model overrides")

from typing import Dict, Optional
from dataclasses import dataclass

import yahp as hp

@dataclass
class MaeVITParams(hp.Hparams):
    image_size: int = hp.required("Image size (after cropping)")

@dataclass
class MAEParams(hp.Hparams):
    lr: float = hp.required("Learning rate")
    weight_decay: float = hp.required("Weight decay")
    t_warmup_factor: int = hp.required("Warmup batches")
    t_max_factor: int = hp.required("Total batches")
    model: str = hp.required("The model type")
    model_overrides: MaeVITParams = hp.required("Model overrides")

class RunParams(hp.Hparams):
    device: str = hp.required("Device")
    precision: str = hp.required("Precision")

    checkpoints: int = hp.required("# Checkpoints")
    evals: int = hp.required("# Evaluations")
    duration: str = hp.required("Duration")

    batch_size: int = hp.required("Batch size")
    micro_batch_size: int = hp.required("Micro batch size")

    batches_per_sec: float = hp.required("Batches per second")
```

Stack trace:
```
Traceback (most recent call last):

  File "train_mae_2d.py", line 65, in <module>
    typer.run(main)

  File "train_mae_2d.py", line 22, in main
    train_cfg = TrainParams.create(config_path, None, cli_args=False)

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/hparams.py", line 122, in create
    return create(cls, data=data, f=f, cli_args=cli_args)

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/create_object/create_object.py", line 625, in create
    hparams, output_f = _get_hparams(constructor=constructor,

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/create_object/create_object.py", line 734, in _get_hparams
    hparams = _create(

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/create_object/create_object.py", line 494, in _create
    obj = _construct_object_from_deferred_create(

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/create_object/create_object.py", line 70, in _construct_object_from_deferred_create
    obj_hparams = _create(

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/create_object/create_object.py", line 156, in _create
    cls.validate_keys(list(data.keys()), allow_missing_keys=True)

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/hparams.py", line 94, in validate_keys
    raise ValueError(f'Unexpected keys in {cls.__name__}: ', extra_keys)

ValueError: ('Unexpected keys in RunParams: ', ['batch_size', 'duration', 'micro_batch_size', 'checkpoints', 'evals', 'dl_workers', 'batches_per_sec', 'precision', 'device'])

(video-rec) ?1 vrec %                                                                                                                                                                                          (main)vrec
(video-rec) ?130 vrec % python3 train_mae_2d.py ./MAE/configs/1x1080TI-base.yml --train-path='~/video_recommendation'                                                                                          (main)vrec
Traceback (most recent call last):
  File "train_mae_2d.py", line 20, in <module>
    TrainParams.register_class("mae", MAEParams)
TypeError: register_class() missing 1 required positional argument: 'class_key'
(video-rec) ?1 vrec %                                                                                                                                                                                          (main)vrec
(video-rec) ?130 vrec %                                                                                                                                                                                        (main)vrec
(video-rec) ?130 vrec % python3 train_mae_2d.py ./MAE/configs/1x1080TI-base.yml --train-path='~/video_recommendation'                                                                                          (main)vrec
Traceback (most recent call last):
  File "train_mae_2d.py", line 20, in <module>
    TrainParams.register_class("mae", MAEParams)
TypeError: register_class() missing 1 required positional argument: 'class_key'
(video-rec) ?1 vrec %                                                                                                                                                                                          (main)vrec
(video-rec) ?130 vrec % python3 train_mae_2d.py ./MAE/configs/1x1080TI-base.yml --train-path='~/video_recommendation'                                                                                          (main)vrec
Traceback (most recent call last):

  File "train_mae_2d.py", line 65, in <module>
    typer.run(main)

  File "train_mae_2d.py", line 22, in main
    train_cfg = TrainParams.create(config_path, None, cli_args=False)

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/hparams.py", line 122, in create
    return create(cls, data=data, f=f, cli_args=cli_args)

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/create_object/create_object.py", line 625, in create
    hparams, output_f = _get_hparams(constructor=constructor,

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/create_object/create_object.py", line 734, in _get_hparams
    hparams = _create(

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/create_object/create_object.py", line 494, in _create
    obj = _construct_object_from_deferred_create(

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/create_object/create_object.py", line 70, in _construct_object_from_deferred_create
    obj_hparams = _create(

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/create_object/create_object.py", line 156, in _create
    cls.validate_keys(list(data.keys()), allow_missing_keys=True)

  File "/home/vedant/miniconda3/envs/video-rec/lib/python3.8/site-packages/yahp/hparams.py", line 94, in validate_keys
    raise ValueError(f'Unexpected keys in {cls.__name__}: ', extra_keys)

ValueError: ('Unexpected keys in RunParams: ', ['micro_batch_size', 'evals', 'batches_per_sec', 'checkpoints', 'dl_workers', 'duration', 'device', 'batch_size', 'precision'])
```

**Comment by vedantroy** [comment]
Issue was not annotating with decorator; maybe throw an error message for this?
