### ISSUE TITLE
Provide a friendly error if an hparam doesn't match the options of a StringEnum 

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/yahp#85]
When using a StringEnum and specifying that as a hyperparameter type for YAHP, it does validate that the YAML argument is a valid option in the StringEnum class. If it isn't, it throws a KeyError. 

It would be nice if it could list out the StringEnum options when it raises the exception. This way, the user can fix the error in their YAML file without digging through the code to see all of the enumerated types.

Traceback below:
```
Traceback (most recent call last):
  File "examples/run_mosaic_trainer.py", line 47, in <module>
    main()
  File "examples/run_mosaic_trainer.py", line 29, in main
    parser = argparse.ArgumentParser(parents=[TrainerHparams.get_argparse(cli_args=True)])
  File "/usr/local/lib/python3.8/dist-packages/yahp/hparams.py", line 127, in get_argparse
    return get_argparse(cls, data=data, f=f, cli_args=cli_args)
  File "/usr/local/lib/python3.8/dist-packages/yahp/create/create.py", line 561, in get_argparse
    _get_hparams(cls=cls, data=data, f=f, remaining_cli_args=remaining_cli_args, argparsers=argparsers)
  File "/usr/local/lib/python3.8/dist-packages/yahp/create/create.py", line 523, in _get_hparams
    return _create(cls=cls,
  File "/usr/local/lib/python3.8/dist-packages/yahp/create/create.py", line 356, in _create
    _create(
  File "/usr/local/lib/python3.8/dist-packages/yahp/create/create.py", line 120, in _create
    kwargs[f.name] = ftype.convert(argparse_or_yaml_value, full_name)
  File "/usr/local/lib/python3.8/dist-packages/yahp/utils/type_helpers.py", line 202, in convert
    return enum_map[val]
KeyError: 'sequenceadg_classification'
```

Instead, I'd want it to be something like:

`ValueError: 'sequenceadg_classification' is not a valid key. Choose one of OPTION_1, OPTION_2, OPTION_3.`

**Comment by mvpatel2000** [comment]
@anisehsani  good to close issue?

**Comment by Averylamp** [comment]
Yup this one should be closed. Thanks!
